apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::767397958941:role/orchestrator-role
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::767397958941:role/orchestrator-role
    spec:
      containers:
      - name: orchestrator
        env:
        - name: AWS_REGION
          value: "ap-south-1"
        - name: ENV
          value: "prod"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator
  annotations:
    alb.ingress.kubernetes.io/group.name: "shared-alb"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-south-1:767397958941:certificate/c02c00eb-b47a-43c3-9370-acad4bc0c931"
    alb.ingress.kubernetes.io/subnets: "subnet-03f8b2a82e958714d, subnet-0b6b6a7c7ac896334"
    alb.ingress.kubernetes.io/tags: "Environment=production"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-2016-08"
spec:
  rules:
  - host: orchestrator-api.goheartbeat.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orchestrator
            port:
              number: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::767397958941:role/orchestrator-role
