apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: services

images:
  - name: 767397958941.dkr.ecr.ap-south-1.amazonaws.com/orchestrator
    newTag: dev-latest

replicas:
  - name: orchestrator
    count: 1

patchesStrategicMerge:
  - config-patch.yaml
